/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Signup = IDL.Record({
  'smsOptIn' : IDL.Bool,
  'cellPhone' : IDL.Text,
  'fullName' : IDL.Text,
  'zipCode' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSignups' : IDL.Func([], [IDL.Vec(Signup)], []),
  'submitSignup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Signup = IDL.Record({
    'smsOptIn' : IDL.Bool,
    'cellPhone' : IDL.Text,
    'fullName' : IDL.Text,
    'zipCode' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSignups' : IDL.Func([], [IDL.Vec(Signup)], []),
    'submitSignup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };